---
# linux config backup

# This simulate collection of running configs in devices
- name: Collect device running configs
  ansible.builtin.shell: "ls -al $HOME && date" # date cmd ensures change in file content
  register: config_output

# - name: Display the stored content
#   ansible.builtin.debug:
#     var: config_output["stdout"]

- name: Save the configuration to the local host /tmp/ file
  ansible.builtin.copy:
    content: "{{ config_output['stdout'] }}"
    dest: "{{ tmp_configs_store }}"
  delegate_to: localhost