---
# Simulate network device running config collection
- name: Simulate Collection of device running configs
  ansible.builtin.shell: "date && ls -al"
  register: config_output

- name: Save the configuration to the temporary config store
  ansible.builtin.copy:
    content: "{{ config_output['stdout'] }}"
    dest: "{{ tmp_config_store }}"
  delegate_to: localhost
