---
# Test tasks to run on remote linux boxes to confirm if role works file
- name: Create a file to write stuff on
  ansible.builtin.file: 
    path: "{{ inventory_hostname }}-config.txt"
    state: touch
  # delegate_to: localhost

- name: Collect some data and write on the file
  ansible.builtin.command:
    cmd: "ls -al >> {{ inventory_hostname }}-config.txt" # Reading a file as test
  # register: linux_config_output

- name: Read the random file
  ansible.builtin.command:
    cmd: "cat {{ inventory_hostname }}-config.txt"
  register: config_output

- name: Display the stored content
  ansible.builtin.debug:
    var: ls_output.stdout