---
# Test tasks to run on remote linux boxes to confirm if role works file
- name: Create a file to write stuff on
  ansible.builtin.file: 
    path: "{{ test_config_file }}"
    state: touch

- name: Collect some data and write on the file
  ansible.builtin.command:
    cmd: " date >> {{ test_config_file }} && ls -al >> {{ test_config_file }}" # Reading a file as test
  # register: linux_config_output

- name: Read the random file
  ansible.builtin.command:
    cmd: "cat {{ test_config_file }}"
  register: config_output