---
# Test tasks to run on remote linux boxes to confirm if role works file
- name: Create a file to write stuff on
  ansible.builtin.shell: "ls -al > /tmp/{{ inventory_hostname }}-config.txt"
  args:
    executable: /bin/bash

- name: Read the file contents
  ansible.builtin.command:
    cmd: "cat /tmp/{{ inventory_hostname }}-config.txt"
  register: config_output

- name: Display the stored content
  ansible.builtin.debug:
    var: config_output.stdout